### PR TITLE
Sb text color

### PR DESCRIPTION
**Pull request by shadoath**

### CODE REVIEW

**Comment by shadoath** [comment]
[Projects for Trello add Text color](https://trello.com/c/x4GXBBvw/753-projects-for-trello-add-text-color)

**Review by strikemike2k — APPROVED** [review]
Nice addition

**Comment by shadoath** [comment]
[{PT} Labels are case insensitive](https://trello.com/c/N7CXKr8v/1017-pt-labels-are-case-insensitive)

**Comment by shadoath** [comment]
[{PT} Downcase, Projects for Trello names](https://trello.com/c/3IS8RRqt/783-pt-downcase-projects-for-trello-names)

**Pull request merged**
